[package]
name = "iced_game_collection"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = {version = "0.13", features = ["tokio"]}
rfd = "0.15.0"
serde =  {version="1.0.210", features = ["derive"]}
serde_json = {version="1.0.128"}
tokio = {version="1", features = ["full"]}
